version: '3'

services:

  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: always
    environment:
      - NODE_ENV=test
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017


volumes:
  mongodata:
